name: EDEN GRID
favicon: null
layout_spectrum: 0.7042083628475666
typography_spectrum: 0.8058392454404384
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dddadd'
    - '#9f9fa8'
    - '#111112'
    - '#615e61'
    - '#542614'
  brandStrength: 0.34306120383553207
  lightness: 0.3788705358747393
  saturation: 0.9487196074333042
  rhythmicContrast: 0.43946181843057275
purpose: []
